### PR TITLE
Improve manual npm deploy/dev experience

### PR DESCRIPTION
**Pull request by strugee**
Adding a shrinkwrap file means that builds are more reproducible because each `npm install` will install the exact same dependency tree regardless of when it's being run and the state of the registry at that time. It also means that deploys can be faster because of `npm ci`.

Adding a `prepare` script cuts out an extra build step because npm will automatically run it after an install. See https://docs.npmjs.com/cli/v6/using-npm/scripts#prepare-and-prepublish

### CODE REVIEW

**Comment by derneuere** [comment]
Okay, I read a bit about npm shrinkwrap and package-lock.json. I think we should also add the package-lock.json file and change the dockerfile to use npm ci instead. If we don't do that, I think we will run into issues with the current dockerfile. Could you add and change that?

**Comment by strugee** [comment]
`package-lock.json` and `npm-shrinkwrap.json` are the same file. The only difference is which one is included in published packages - the lockfile is always ignored and the shrinkwrap file is always included (I think you can ignore it maybe, but basically always). In fact if you already have a lockfile, running `npm shrinkwrap` literally just renames `package-lock.json` to `npm-shrinkwrap.json`.

So it doesn't make sense to have both of them at the same time - it'll probably also confuse npm. We want to use the shrinkwrap file because it's best practice for apps to use the shrinkwrap file and for libraries to use the lockfile. (The reason is because when you're writing a library, you want to make sure developers and CI are using the same dependency tree, but you don't want to force consumers of the library to have to use a particular dep tree - e.g. if there was a security issue with a transient dependency, your consumer would have to fork your library just to pull in a fixed version. By contrast with an app the entire dep tree is your responsibility always, so you want to use a shrinkwrap file so the same dep tree is used everywhere, including in production.)

`npm ci` is also not strictly necessary. `npm install` will still respect the shrinkwrap file. `npm ci` is just a faster version of `npm install` - it works by not really bothering to resolve the dep tree with what's in `node_modules/` at all, and instead just completely blowing away `node_modules/` and blasting a new version onto disk as fast as possible. This only works if npm doesn't have to spend time computing the dep tree, which is why it only works with a shrinkwrap file/lockfile. But all install commands will still respect `npm-shrinkwrap.json`.

I can add `npm ci` to the `Dockerfile` when I'm in front of my laptop, but this PR should be mergeable as-is since it's just a performance enhancement. So it's up to you if you want to wait for me to add it. If not I'll just get it in a follow-up PR 👍

**Comment by derneuere** [comment]
Okay, thanks for the explanation! 👍

**Comment by strugee** [comment]
Any time! :tada: thanks for merging :-)

**Pull request merged**
