### PR TITLE
update mantine to v5.2.0

### PR DESCRIPTION
**Pull request by sickelap**
This is not a small change and I did my best to verify the majority of views visually. It might be that I missed something.
I'd appreciate any testing and feedback.

### CODE REVIEW

**Comment by derneuere** [comment]
Thanks for implementing this! Found a couple of bugs: 

CustomSearch:
- Popup doesn't close if it is unfocused or enter is hit
- Persons are missing from results
- Instead of being one panel, it's multiple single entries with rounded corners 

Faces:
- On first view of the faces page the tab labeled is selected, but inferred faces are shown

Footer:
- Clicking on an icon, switches the site and opens up the popover. It should instead either open up a site or open up a popover instead

WorkerIndicator:
- When hovering over the indicator, the popup spawns correctly, but Popup Pointer isn't at the correct place

AutoAlbum:
- Delete Button is directly on the image of the auto album and not within the dropdown menu

TopMenu:
- The avatar menu is no longer shown on hover. That's fine, but there should be an indication, that the avatar is clickable, when you hover over it

**Comment by sickelap** [comment]
Thanks for looking into this. I'll be addressing the listed issues.

**Comment by sickelap** [comment]
Addressed all issues except the CustomSearch. This one seems more challenging

**Comment by derneuere** [comment]
Do you need help? What's the issue? 😅

**Comment by sickelap** [comment]
I got sick very bad, and need time to recover. I will pick this up as soon as I'm able to think straight.

**Comment by derneuere** [comment]
Take your time and get well soon! 🤗

**Comment by derneuere** [comment]
Most things look like they are fixed :+1: 

CustomSearch:
- I can only sometimes click on a search result and find something. It looks like a focusing issue
- If I am able to click on a search result, it's issuing a ton of request to query /list

**Comment by sickelap** [comment]
Thanks for testing. I'll look into outstanding issues.

**Pull request closed without merging**
