### PR TITLE
fix: #490 attempt to refresh access token upon invalidation

### PR DESCRIPTION
**Pull request by polaroidkidd**
https://github.com/LibrePhotos/librephotos/issues/490#issuecomment-1105790357

### CODE REVIEW

**Comment by derneuere** [comment]
Works when you logged in and browse around the page :+1:  One issue still persists: If you close the page and wait for the access token to expire and then open the page again, it will still log you out before trying to refresh first.

**Comment by derneuere** [comment]
The general logoin redirect happens here: https://github.com/LibrePhotos/librephotos-frontend/blob/dev/src/layouts/PrivateRoute.js

**Comment by derneuere** [comment]
If I comment out the redirect part it works. It's probably something wrong with "isRefreshTokenExpired". 
Another issue is then, that I get spammed every time a request is not authenticated :sweat_smile: I think we somehow have to ignore 401 errors.

**Comment by polaroidkidd** [comment]
> The general logoin redirect happens here: https://github.com/LibrePhotos/librephotos-frontend/blob/dev/src/layouts/PrivateRoute.js

Might as well refactor `PrivateRoute.js`

**Comment by polaroidkidd** [comment]
> Works when you logged in and browse around the page +1 One issue still persists: If you close the page and wait for the access token to expire and then open the page again, it will still log you out before trying to refresh first.

hmm.. it looks like the refresh form the RTK-Query and the refresh in the `apiClient.js`file are competing during the login..

**Comment by polaroidkidd** [comment]
I think the refresh call from the `apiClient.js` is colliding with the refresh call from the `api.ts`. There's two calls happening when you navigate to the page again after being logged out. Looks like it's a bit more complicated than anticipated.

**Comment by polaroidkidd** [comment]
right, so I removed the dispatch to logout of there's no refresh token in the store which seems to fix the issue of being logged out if you navigate back to the page.

**Comment by derneuere** [comment]
Found a small bug, but I also found the fix for that, so I will add that myself :) Otherwise it looks good :+1:

**Pull request merged**
