### PR TITLE
update mantine dependency, rework settings UI

### PR DESCRIPTION
**Pull request by jcalado**

### CODE REVIEW

**Comment by jcalado** [comment]
Settings will look like this:

image

**Comment by sickelap** [comment]
Tested, looks good.
If you can, you could try to fix e2e tests as we have them for settings page. If not, I'll do this later.

@derneuere @DigitalWarrior

**Comment by sickelap** [comment]
I had something similar in mind. But with tabs or some other form of grouping. I dislike the fact that there's no space at the bottom. Transcode switch seems abandoned. Maybe adding some space at the bottom would help?

**Comment by jcalado** [comment]
Agree. I also toyed with the idea of tabs, but seems like we'de be hiding the options again. Just not on the selects.

Good idea with the spacing on the bottom. I'll tweak it and push the changes.

**Comment by sickelap** [comment]
That looks nice. I'll update e2e tests after the merge. Or, if you feel brave, you could give it a go. :)

**Comment by jcalado** [comment]
Thanks @sickelap for the help with the tests :)

**Pull request merged**
