### PR TITLE
Redesign profile

### PR DESCRIPTION
**Pull request by jcalado**

### CODE REVIEW

**Comment by jcalado** [comment]
Consistent with the rest of my UI changes, should look like this:

image

**Comment by derneuere** [comment]
Layout looks very good!

Public Avatar should be at the first position, and it's the same category as user. Public sharing should also be in the category user.

Language Selection should be in the category "Appearance". I think it also makes sense to change the color scheme button to the radio buttons to be more consistent

**Comment by jcalado** [comment]
@derneuere thanks, I've changed things around a bit based on your feedback.

**Comment by derneuere** [comment]
Looks good!

**Pull request merged**
