### PR TITLE
Add sort by date on faces dashboard

### PR DESCRIPTION
**Pull request by 5m4u66y**
Working on implementing feature request /LibrePhotos/librephotos#655
Depends on LibrePhotos/librephotos#671

I still have a few issues to fix before validating this PR.
The faces don't refresh when selecting a different sort option, and for know I don't get why.
Also, minor issue, the Divider I added to the toolbar doesn't appear.
And need to add translation.

### CODE REVIEW

**Comment by derneuere** [comment]
You probably have to reset the redux store for the faces when you switch the order. 

We currently have one query to fetch the names and the number of photos per person and another query that is paginated where you can fetch a page for a person. That way, I can render basically an unlimited amount of faces.

**Comment by derneuere** [comment]
Hey, I figured out the main issue. You have to reload the incomplete faces, when you change the order_by:

```
  useEffect(() => {
    dispatch(api.endpoints.fetchIncompleteFaces.initiate({ inferred: false }, { forceRefetch: true }));
    dispatch(api.endpoints.fetchIncompleteFaces.initiate({ inferred: true }, { forceRefetch: true }));
    fetchGroupFaces(true);
  }, [orderBy]);
```

You now only have to figure out, why he doesn't fetch the right groups immediately and only on scroll.

**Comment by 5m4u66y** [comment]
I ended up mixing both of my implementations, because I couldn't get it to work smoothly. And I believe that it is better to sort already loaded faces on the client. Correct me if I am wrong. The faces lists are only sorted again when the user changes the sort option, and there is no need to reload anything from the backend.
I tested it on a large photo library, and I don't see any performance difference compared to the version before this feature.
There is still one problem I need to deal with : changing sort option when not all the faces are loaded for a given person. Maybe in this case, I need to clear already loaded faces for that person. Other ideas?

**Comment by derneuere** [comment]
I think clearing them is a good option. Just overwrite the incomplete with temp elements, and then it should probably work alright :) Here is the snippet on how we did it when loading the structure:
https://github.com/LibrePhotos/librephotos-frontend/blob/eb8274ec09f44730101e6c1bf4123b3eeb4fa85b/src/store/faces/faceSlice.ts#L24-L39

**Comment by 5m4u66y** [comment]
For a person that has more than 100 faces and if they are not all loaded when changing orderBy setting, I now clear all the faces already loaded. I also needed to force refetch the faces in this case. I didn't find an easy way to do it only for persons having partly loaded faces, so I do it for all persons having more than 100 faces.
When changing orderBy and meeting this condition, the screen refreshes with visible cells being blanked. The user then has to scroll a bit to load the faces again. I didn't find a way to avoid this, and don't think I will (anyway, it already behave the same when stoping fast scrolling, you then have to scroll a bit to load the faces). Fixing this would require to get the current grid position, and dispatch a fetchFaces for the required persons and pages. That is a bit beyond my current knowledge of React and Libre-Photos code.

**Comment by derneuere** [comment]
Looks fine to me, for now :) If you fix the merge conflict, then I think we can merge it :+1:

**Pull request merged**
