### PR TITLE
refactor username validation

### PR DESCRIPTION
**Pull request by sickelap**

### CODE REVIEW

**Comment by derneuere** [comment]
I think this broke the first time setup 😅 

image

**Comment by sickelap** [comment]
I'll look into this

**Comment by derneuere** [comment]
The key now works, but I still can't edit person attributes, as the validation will complain, that the user already exists.
In the following screenshot, I just want to change the path:
image

**Comment by sickelap** [comment]
I'll check that

**Comment by sickelap** [comment]
fix is in PR https://github.com/LibrePhotos/librephotos-frontend/pull/401

**Comment by derneuere** [comment]
@sickelap works again! Thank you :)

**Pull request merged**
