### PR TITLE
library UI rework

### PR DESCRIPTION
**Pull request by jcalado**

### CODE REVIEW

**Comment by jcalado** [comment]
Looking for some feedback on this, @derneuere :)
Thanks!

**Comment by sickelap** [comment]
The rework looks great. Well done!

Few notes:

Please resolve conflicts and mark PR as ready for review when it's ready, at the moment it is a draft.

For the change itself:
- I think the status for Nextcloud should not be set to ready while the directory listing is being retrieved. Currently, it's displaying different color icon when directory retrieval is in progress.
- The Nextcloud status icon should not be a button.
- Something need to be done with the button to change Nextcloud directory (see attached image). It won't fit nicely if the folder name is long.
- Question mark icon next to Scan Library heading on the dark theme is barely visible
- The info icon on faces tile serves little purpose. Instead, you could display a dropdown with statistics for faces when mouse hovering on the tile. If on mobile this will work by tapping on the tile then it's fine, otherwise I would not bother making it work there. I think cleaner interface is more important than showing everything on already restricted real estate space.

image

**Comment by jcalado** [comment]
Ok, so [4b1ea62](https://github.com/LibrePhotos/librephotos-frontend/pull/173/commits/4b1ea629126ae370fe831239e00b5d1a6ea7dfb8) addresses most of the feedback.

- Faces info button is removed in favor of the complete info card being an hoverable element.

image

- Changed the nextcloud status info with a badge, it reads from `userSelfDetails.nextcloud_scan_directory`. If not set, it shows "disconnected". If set shows "ok".
- Moved the information about what folder is actually selected to the second line of the label on the left instead of it being inside the button. Button always show "browse" now.

image

Still need to resolve conflicts, though.

**Comment by sickelap** [comment]
I'll test it as soon as it's rebased

**Comment by jcalado** [comment]
Still unsure on what to do about the newly introduced strings. Do I have to manually get them into en/translation.json? How do they propagate to the other language .json files?

**Comment by sickelap** [comment]
I like the rework. Nice one.  I noticed a couple more things.
- The buttons do not look obvious, could you try adding an outline?
- To make it clearer, the status of Nextcloud could say “not connected”/“disconnected”, “connecting” and “connected”. Also, the colors could indicate the status. e.g., red, yellow/orange, and green respectively.

**Comment by derneuere** [comment]
Another comment from me: I think the merge went wrong, it seems to undo most of the bug fixes I made / the new motion images feature

**Comment by jcalado** [comment]
You're absolutely right I think i messed that up. Should be ok now?

**Comment by derneuere** [comment]
Ah, you probably did not get a notification. 
Looks good to me, if you address the points @sickelap  made, I will merge it :)

**Comment by jcalado** [comment]
- Colors are coming from `nextcloudStatusColor`.
- Buttons have been changed to outline
- Nextcloud status now has Connecting, connected, error.

**Comment by sickelap** [comment]
Thanks for the update. I tested and would like to suggest changing the text “Error” to “Not Connected” as it is better UX, especially because we are not explaining what the error actually is.

**Comment by jcalado** [comment]
> Thanks for the update. I tested and would like to suggest changing the text “Error” to “Not Connected” as it is better UX, especially because we are not explaining what the error actually is.

done. 
Still need some help with out to get the strings out of the code and into the i18n system, otherwise this looks like it's done.

**Comment by sickelap** [comment]
There are two keys for Nextcloud in i18n that are already defined. `settings.nextcloudloggedin` and `settings.nextcloudnotloggedin`. They have content "OK" and "Dicsonnected" in English. You could update "OK" one to "Connected" and add another key, say `settings.nextcloudconnecting` with content of "Connecting".

And the use would be like so:

```jsx
                {isNextcloudFetching && t("settings.nextcloudconnecting")}
                {isNextcloudSuccess && !isNextcloudFetching && t("settings.nextcloudloggedin")}
                {isNextcloudError && t("settings.nextcloudnotloggedin")}
```

Until translated, other languages will see the content key only. That means in language where the has not been translated the content will show as `settings.nextcloudconnecting`

**Comment by jcalado** [comment]
Thanks @sickelap :) Pushed. Ready to merge.

**Comment by derneuere** [comment]
👍

**Pull request merged**
