### PR TITLE
Feat/ts migration

### PR DESCRIPTION
**Pull request by polaroidkidd**
migrating user actions & reducer to TS and RTK

### CODE REVIEW

**Comment by polaroidkidd** [comment]
still have an error to fix
`Uncaught TypeError: property "scan_directory" is non-configurable and can't be deleted`

also, I messed up the commit history. I'll have to fix that too.

**Comment by polaroidkidd** [comment]
ok, so this got a tad bigger than anticipated. This PR does the following:

  * migrate redux user slice to redux-toolkit
  * migrate user api requests to rtk-query
  * clean up redux store creation (and add userApi generated by rtk-query)
  * clean up redux generated hooks (they were duplicated in the `src/hooks.ts`file as well as the `src/store.ts` file. I've moved them to the `src/store/store.ts` file (that's where the majority of changes comes from)
  * created a `userSelectors.ts` file and created a selector for the use-slice based on the [redux toolkit docs](https://redux-toolkit.js.org/api/createSelector).
  * fixed the merge/commit mash-up

**Comment by derneuere** [comment]
Looks good :+1:  Only found these two commented lines of code. Tested the code and it worked on my part. I will merge it after these small changes :D

**Comment by polaroidkidd** [comment]
do the commits get squashed during the merge?

**Comment by derneuere** [comment]
No, I will only merge them :)

**Comment by polaroidkidd** [comment]
Ah ok. I usually only have the merge commits in the master branch, but if you're happy with the commits amthen that's good enough for me.

**Pull request merged**
